Pipeline completo

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -121,26 +121,40 @@ jobs:
       - name: Install Project Dependencies
         run: npm ci
 
-      - name: Dependency Check
-        uses: dependency-check/Dependency-Check_Action@1.1.0
-        env:
-          JAVA_HOME: /opt/jdk
-        id: Depcheck
-        with:
-          project: '${{ github.event.repository.name }}'
-          path: '.'
-          format: 'HTML'
-          args: >
-            --out ./reports
-            --failOnCVSS 7
-            --enableRetired
+      # - name: Dependency Check
+      #   uses: dependency-check/Dependency-Check_Action@1.1.0
+      #   env:
+      #     JAVA_HOME: /opt/jdk
+      #   id: Depcheck
+      #   with:
+      #     project: '${{ github.event.repository.name }}'
+      #     path: '.'
+      #     format: 'HTML'
+      #     args: >
+      #       --out ./reports
+      #       --failOnCVSS 7
+      #       --enableRetired
       
-      - name: Detener si Hay Vulnerabilidades
+      # - name: Detener si Hay Vulnerabilidades
+      #   run: |
+      #     if [ $? -ne 0 ]; then
+      #       echo "Vulnerabilidades críticas detectadas en Dependency Check."
+      #       exit 1
+      #     fi
+
+      # Ejecutar OWASP Dependency-Check con Control
+      - name: Ejecutar OWASP Dependency-Check con `exit 1`
         run: |
-          if [ $? -ne 0 ]; then
-            echo "Vulnerabilidades críticas detectadas en Dependency Check."
-            exit 1
-          fi
+          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
+          unzip dependency-check-8.4.0-release.zip
+          
+          # Ejecutar Dependency Check con failOnCVSS y Exit 1
+          ./dependency-check/bin/dependency-check.sh \
+            --project "MyProject" \
+            --scan . \
+            --out reports \
+            --failOnCVSS 7 \
+            --enableRetired || exit 1
 
       - name: Upload Test Result
         uses: actions/upload-artifact@master
